version: '3.7'
services:
  nginx-rtmp:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-rtmp
    ports:
      - "1935:1935"
      - "81:80"
    volumes:
      - ./hls:/var/www/html/hls
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_bridge_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: phat_guest
      RABBITMQ_DEFAULT_PASS: MatKhau24CuaP02hatD123aiLam
    ports:
      - "5672:5672"  
      - "15672:15672"  
    networks:
      - my_bridge_network
    
  minio:
    image: quay.io/minio/minio:RELEASE.2024-07-10T18-41-49Z
    container_name: minio
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: MatKhau24CuaP02hatD123aiLam
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001' 
      MINIO_NOTIFY_AMQP_ENABLE_upload: 'on'
      MINIO_NOTIFY_AMQP_URL_upload: 'amqp://phat_guest:MatKhau24CuaP02hatD123aiLam@rabbitmq:5672'
      MINIO_NOTIFY_AMQP_EXCHANGE_upload: 'minio-events'
      MINIO_NOTIFY_AMQP_ROUTING_KEY_upload: 'video.uploaded'
      MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_upload: 'direct'
    command: minio server /data
    depends_on:
      - rabbitmq
    networks:
      - my_bridge_network

  uploader:
    build:
      context: .
      dockerfile: Dockerfile.uploader
    container_name: hls-uploader
    volumes:
      - ./hls:/watch/hls
    networks:
      - my_bridge_network
    depends_on:
      - nginx-rtmp
      - minio
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minio_user
      - MINIO_SECRET_KEY=MatKhau24CuaP02hatD123aiLam
      - WATCH_DIR=/watch/hls

networks:
  my_bridge_network:
    driver: bridge